use_frameworks!

platform :ios, '10.0'

target 'ZYCObjc_Example' do
  pod 'ZYCObjc', :path => '../'

  target 'ZYCObjc_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
